# Generated by Django 4.0.5 on 2022-06-12 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_comment_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='YVES', max_length=120)),
                ('body', models.TextField(verbose_name='Réponse')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='Date replyed')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='post.comment')),
            ],
        ),
    ]
