# Generated by Django 4.0.5 on 2022-06-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_commentresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.CharField(max_length=300, verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='commentresponse',
            name='body',
            field=models.CharField(max_length=300, verbose_name='Réponse'),
        ),
    ]
