# Generated by Django 4.0.5 on 2022-06-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_comment_body_alter_commentresponse_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='commentresponse',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pk',)},
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image'),
        ),
    ]
