# Generated by Django 4.0.5 on 2022-06-13 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_comment_options_alter_commentresponse_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
